micronaut:
  application:
    name: estudosMicronaut
  server:
    port: 9090

flyway:
  locations:
      classpath: 'db/migration/'
  database-name: postgres
  enabled: true

# Data Source Configuration
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/EstudosMicro
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
    schema-generate: UPDATE
    dialect: io.micronaut.data.model.query.builder.sql.Dialect.POSTGRES

mongodb:
  uri : mongodb://127.0.0.1:27017/EstudosMicronaut

redis:
  uri: redis://192.168.20.205:6379

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        default_schema: public
    packages-to-scan:
      - 'com.phoebus'
    entity-scan:
      packages: 'com.phoebus.entites'


