micronaut:
  application:
    name: estudosMicronaut
  server:
    port: 9090

flyway:
  locations:
      classpath: 'db/migration/'
  database-name: postgres
  enabled: true

# Data Source Configuration
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/EstudosMicro
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
    schema-generate: UPDATE
    dialect: io.micronaut.data.model.query.builder.sql.Dialect.POSTGRES
    hikari:
      minimum-idle: 5 #Número mínimo de conexões ociosas que HikariCP tenta manter no pool.
      maximum-pool-size: 20 #Número máximo de conexões no pool.
      idle-timeout: 300000 #Tempo máximo que uma conexão ociosa pode permanecer no pool antes de ser removida (em milissegundos).
      max-lifetime: 1800000 # Tempo máximo de vida útil para uma conexão no pool (em milissegundos).
      connection-timeout: 30000 #Tempo máximo que o HikariCP espera para obter uma conexão do pool (em milissegundos).
      pool-name: MeuHikariPool # Nome do pool de conexões.



mongodb:
  uri : mongodb://127.0.0.1:27017/EstudosMicronaut

redis:
  uri: redis://192.168.20.205:6379

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        default_schema: public
        show_sql: true
        format_sql: true
        use_sql_comments: true
    packages-to-scan:
      - 'com.phoebus'
    entity-scan:
      packages: 'com.phoebus.entites'
