micronaut:
  application:
    name: estudosMicronaut
  server:
    port: 9090
  multipart:
    enabled: true


liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/migration/changelog/liquibase-changelog.xml'

# Data Source Configuration
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/EstudosMicronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
    dialect: io.micronaut.data.model.query.builder.sql.Dialect.POSTGRES
    hikari:
      minimum-idle: 5 #Número mínimo de conexões ociosas que HikariCP tenta manter no pool.
      maximum-pool-size: 20 #Número máximo de conexões no pool.
      idle-timeout: 30000000 #Tempo máximo que uma conexão ociosa pode permanecer no pool antes de ser removida (em milissegundos).
      max-lifetime: 18000000 # Tempo máximo de vida útil para uma conexão no pool (em milissegundos).
      connection-timeout: 30000 #Tempo máximo que o HikariCP espera para obter uma conexão do pool (em milissegundos).
      pool-name: MeuHikariPool # Nome do pool de conexões.
    logging:
      level: DEBUG # Define o nível de logging para o datasource

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update           # Define o comportamento de geração do esquema de banco de dados.
        default_schema: public   # Define o esquema padrão a ser usado pelo Hibernate.
        show_sql: true           # Habilita a exibição das instruções SQL geradas no console.
        format_sql: true         # Habilita a formatação das instruções SQL exibidas no console.
        use_sql_comments: true   # Habilita o uso de comentários nas instruções SQL para ajudar na depuração.
        jdbc.lob.non_contextual_creation: true            # Necessário para suporte a LOB no PostgreSQL.
    packages-to-scan:
      - 'com.phoebus.model'            # Define os pacotes que devem ser escaneados para encontrar entidades JPA.
    entity-scan:
      packages: 'com.phoebus.model.entites'  # Define os pacotes que contêm entidades JPA para serem escaneadas.
